In [145]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [147]:
from google.colab import drive
drive.mount("/content/drive")
df = pd.read_csv('/content/drive/My Drive/messy data.csv')
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

# **Data_Understanding**

In [152]:
# Check rows, columns, column names, and data types
print("Rows and Columns:", df.shape)
print()

print("Column Names:")
print(df.columns.tolist())
print()

print("Data Types:")
print(df.dtypes)
# Basic information
print("Dataset Information:")
df.info()
# Statistical summary of numerical columns
df.describe()
# index
print(df.index)
# Unique values in important columns
important_cols = ["Category", "Sub-Category", "Segment", "Region"]

for col in important_cols:
    print(col, "unique values:")
    print(df[col].unique().tolist())
    print()

Rows and Columns: (10044, 21)

Column Names:
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit']

Data Types:
Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code      float64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object
Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10044 entries, 0 to 10043
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         10044 non-null  int64
 1   Order ID       10044 non-null  object
 2   Order Date     10044 non-null  object
 3   Ship Date      10044 non-null  object
 4   Ship Mode      10044 non-null  object
 5   Customer ID    10044 non-null  object
 6   Customer Name  10004 non-null  object
 7   Segment        10044 non-null  object
 8   Country        10044 non-null  object
 9   City           10044 non-null  object
 10  State          10044 non-null  object
 11  Postal Code    10004 non-null  float64
 12  Region         10044 non-null  object
 13  Product ID     10044 non-null  object
 14  Category       10044 non-null  object
 15  Sub-Category   10044 non-null  object
 16  Product Name   10044 non-null  object
 17  Sales          10004 non-null  float64
 18  Quantity       10044 non-null  int64
 19  Discount       10044 non-null  float64
 20  Profit         10004 non-null  float64
dtypes: float64(4), int64(2), object(15)
memory usage: 1.6+ MB
RangeIndex(start=0, stop=10044, step=1)
Category unique values:
['Furniture', 'Office Supplies', 'Technology', 'office supplies', 'technology', 'furniture']

Sub-Category unique values:
['Bookcases', 'Chairs', 'Labels', 'Tables', 'Storage', 'Furnishings', 'Art', 'Phones', 'Binders', 'Appliances', 'Paper', 'Accessories', 'Envelopes', 'Fasteners', 'Supplies', 'Machines', 'Copiers']

Segment unique values:
['Consumer', 'Corporate', 'Home Office']

Region unique values:
['South', 'West', 'Central', 'East']

In [153]:
#important summary
rows, columns = df.shape
total_sales = df["Sales"].sum()
highest_sales_category = df.groupby("Category")["Sales"].sum().idxmax()
print("1. Rows and columns in dataset=", rows, "rows and", columns, "columns")
print("2. Total sales are=", total_sales)
print("3. Category with highest sales:", highest_sales_category)

1. Rows and columns in dataset= 10044 rows and 21 columns
2. Total sales are= 2552102.8119
3. Category with highest sales: Technology

# **Data Quality Assessment**

In [160]:
#finding the missing value
missing_value=df.isnull().sum()
print("Missing Value in each column:")
print(missing_value)
print("Rows that have missing values=\n",df[df.isnull().any(axis=1)].head())
print()

# finding duplicate values
duplicate_rows = df.duplicated().sum()
print("Duplicate rows:", duplicate_rows)

Missing Value in each column:
Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name    40
Segment           0
Country           0
City              0
State             0
Postal Code      40
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales            40
Quantity          0
Discount          0
Profit           40
dtype: int64
Rows that have missing values=
      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
9        10  CA-2014-115812    6/9/2014   6/14/2014  Standard Class
203     204  US-2017-116701  12/17/2017  12/21/2017    Second Class
279     280  CA-2017-132976  10/13/2017  10/17/2017  Standard Class
289     290  CA-2016-110772  11/20/2016  11/24/2016    Second Class
301     302  CA-2016-142545  10/28/2016   11/3/2016  Standard Class

    Customer ID     Customer Name      Segment        Country          City  \
9      BH-11710   Brosina Hoffman     Consumer  United States   Los Angeles
203    LC-17140      Logan Currie     Consumer  United States        Dallas
279    AG-10495               NaN    Corporate  United States  Philadelphia
289    NZ-18565     Nick Zandusky  Home Office  United States      Columbus
301    JD-15895  Jonathan Doherty    Corporate  United States    Belleville

     ... Postal Code   Region       Product ID         Category Sub-Category  \
9    ...         NaN     West  OFF-AP-10002892  Office Supplies   Appliances
203  ...         NaN  Central  OFF-AP-10003217  Office Supplies   Appliances
279  ...     19140.0     East  OFF-LA-10002043  Office Supplies       Labels
289  ...     43229.0     East  OFF-FA-10002983  Office Supplies    Fasteners
301  ...      7109.0     East  FUR-FU-10001861        Furniture  Furnishings

                                          Product Name    Sales  Quantity  \
9                     Belkin F5C206VTEL 6 Outlet Surge  114.900         5
203               Eureka Sanitaire  Commercial Upright   66.284         2
279                                          Avery 489   24.840         3
289                     Advantus SlideClip Paper Clips   19.096         7
301  Floodlight Indoor Halogen Bulbs, 1 Bulb per Pa...      NaN         4

     Discount    Profit
9         0.0   34.4700
203       0.8 -178.9668
279       0.2    8.6940
289       0.2       NaN
301       0.0   38.0240

[5 rows x 21 columns]

Duplicate rows: 48

In [159]:
# 3. Inspect numerical columns
num_cols = df.select_dtypes(include="number").columns
print(num_cols)
print("Summary of Numerical Column is =")
print(df[num_cols].describe())
print()

print("Minimum value of sale is =", df["Sales"].min())
print("Maximum Value of sales is = ", df["Sales"].max())
print("Average Profit is =", df["Profit"].mean())
print("Maximum Discount:", df["Discount"].max())

Index(['Row ID', 'Postal Code', 'Sales', 'Quantity', 'Discount', 'Profit'], dtype='object')
Summary of Numerical Column is =
             Row ID   Postal Code          Sales      Quantity      Discount  \
count  10044.000000  10004.000000   10004.000000  10044.000000  10044.000000
mean    4994.465253  55154.199320     255.108238      3.790422      0.156261
std     2885.342882  32037.893863    1702.917481      2.224568      0.206516
min        1.000000   1040.000000       0.444000      1.000000      0.000000
25%     2497.750000  23223.000000      17.332500      2.000000      0.000000
50%     4989.500000  55901.000000      54.780000      3.000000      0.200000
75%     7492.250000  90008.000000     209.970000      5.000000      0.200000
max     9994.000000  99301.000000  121504.000000     14.000000      0.800000

             Profit
count  10004.000000
mean      28.667871
std      233.940828
min    -6599.978000
25%        1.713750
50%        8.636000
75%       29.331600
max     8399.976000

Minimum value of sale is = 0.444
Maximum Value of sales is =  121504.0
Average Profit is = 28.667870531787283
Maximum Discount: 0.8

In [161]:
# 4. Inspect important categorical columns
cat_cols = ["Category", "Region", "Segment",'Sub-Category']

for col in cat_cols:
    print(col, "value counts:")
    print(df[col].value_counts())
    print()

category_most_records = df["Category"].value_counts().idxmax()
segment_most_frequent = df["Segment"].value_counts().idxmax()
region_fewest_records = df["Region"].value_counts().idxmin()

print("Category with most records:", category_most_records)
print("Segment appearing most frequently:", segment_most_frequent)
print("Region with fewest records:", region_fewest_records)

Category value counts:
Category
Office Supplies    5994
Furniture          2113
Technology         1837
office supplies      61
furniture            20
technology           19
Name: count, dtype: int64

Region value counts:
Region
West       3219
East       2860
Central    2335
South      1630
Name: count, dtype: int64

Segment value counts:
Segment
Consumer       5212
Corporate      3039
Home Office    1793
Name: count, dtype: int64

Sub-Category value counts:
Sub-Category
Binders        1530
Paper          1376
Furnishings     964
Phones          895
Storage         849
Art             802
Accessories     778
Chairs          621
Appliances      469
Labels          366
Tables          320
Envelopes       254
Bookcases       228
Fasteners       219
Supplies        190
Machines        115
Copiers          68
Name: count, dtype: int64

Category with most records: Office Supplies
Segment appearing most frequently: Consumer
Region with fewest records: South

In [162]:
# date column
print("Date Columns DataType")
print(df[["Order Date","Ship Date"]].dtypes)
print()
if(df["Order Date"].dtype == 'object' or (df["Ship Date"].dtype == 'object')):
  print("Dates are stored in text, so conversion is required later")
else:
    print("Dates are already in text form")

Date Columns DataType
Order Date    object
Ship Date     object
dtype: object

Dates are stored in text, so conversion is required later

In [163]:
#DATA QUALITY REPORT
print("DATA QUALITY REPORT")
print("="*80)
print("1. Missing Values Summary")
print(missing_value[missing_value>0])
print()

print("2. Duplicate Records Summary")
print("Duplicate row found:",duplicate_rows)
print()

print("3. No. of Rows and Columns")
print("Rows and Columns=",df.shape)
print()

print("4. Numercial Column Observation")
print("Minimum Sales:",df["Sales"].min())
print("Maximum Sales:",df["Sales"].min())
print("Average Profit:",df["Profit"].mean())
print("Maximum Discount:",df["Discount"].max())
print()

print("5. Date Column Observation")
print("Order Date Type:",df["Order Date"].dtype)
print("ship Date Type:",df["Ship Date"].dtype)
print()

print("6. Categorical Column Observations")
print("Category with most records:", category_most_records)
print("Segment appearing most frequently:", segment_most_frequent)
print("Region with fewest records:", region_fewest_records)
print()

print("7. Final Conclusion")
print("Missing values should be handled before analysis")
print("The Dataset contain rows and columns:",df.shape)
print("Dulpicate Records should be removed")
print("Numercial column should be checked")
print("Dates should be converted into Date Format")

DATA QUALITY REPORT
================================================================================
1. Missing Values Summary
Customer Name    40
Postal Code      40
Sales            40
Profit           40
dtype: int64

2. Duplicate Records Summary
Duplicate row found: 48

3. No. of Rows and Columns
Rows and Columns= (10044, 21)

4. Numercial Column Observation
Minimum Sales: 0.444
Maximum Sales: 0.444
Average Profit: 28.667870531787283
Maximum Discount: 0.8

5. Date Column Observation
Order Date Type: object
ship Date Type: object

6. Categorical Column Observations
Category with most records: Office Supplies
Segment appearing most frequently: Consumer
Region with fewest records: South

7. Final Conclusion
Missing values should be handled before analysis
The Dataset contain rows and columns: (10044, 21)
Dulpicate Records should be removed
Numercial column should be checked
Dates should be converted into Date Format

# **Data Cleaning**

In [164]:
#creating a copy for cleaning the dataset
sales_clean = df.copy()
duplicate_before= sales_clean.duplicated().sum()
missing_before = sales_clean.isnull().sum()
rows_before = sales_clean.shape[0]
print("Duplicate row before cleaning is =",duplicate_before)
print("Missing values before cleaning:")
print(missing_before[missing_before > 0])
print("Rows before cleaning:",rows_before)
print()

#Outlier Concept
print("="*50)
print("Detecting the Outliers")
print("="*50)
numeric_cols = df.select_dtypes(include="number").drop(columns=["Sales","Quantity","Discount"]).columns
#formula IQR
#Outlier Concept
for column in numeric_cols:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[(df[column] < lower_bound) | (df[column] > upper_bound)]

    print("-" * 40)
    print("Column=",column)
    print("Lower Bound=", lower_bound)
    print("Upper Bound=", upper_bound)
    print("Number of Outliers=", outliers.shape[0])
    print("Min value=",df[column].min())
    print("Max value=",df[column].max())
    print("-" * 40)

# dealing with quantity sales and discount because can't be in the negative values
cols=["Quantity","Sales","Discount"]
for column in cols:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    lower_bound=max(0,lower_bound)
    outliers = df[(df[column] < lower_bound) | (df[column] > upper_bound)]

    print("-" * 40)
    print("Column=",column)
    print("Lower Bound=", lower_bound)
    print("Upper Bound=", upper_bound)
    print("Number of Outliers=", outliers.shape[0])
    print("Min value=",df[column].min())
    print("Max value=",df[column].max())
    print("-" * 40)

Duplicate row before cleaning is = 48
Missing values before cleaning:
Customer Name    40
Postal Code      40
Sales            40
Profit           40
dtype: int64
Rows before cleaning: 10044

==================================================
Detecting the Outliers
==================================================
----------------------------------------
Column= Row ID
Lower Bound= -4994.0
Upper Bound= 14984.0
Number of Outliers= 0
Min value= 1
Max value= 9994
----------------------------------------
----------------------------------------
Column= Postal Code
Lower Bound= -76954.5
Upper Bound= 190185.5
Number of Outliers= 0
Min value= 1040.0
Max value= 99301.0
----------------------------------------
----------------------------------------
Column= Profit
Lower Bound= -39.713024999999995
Upper Bound= 70.75837499999999
Number of Outliers= 1881
Min value= -6599.978
Max value= 8399.976
----------------------------------------
----------------------------------------
Column= Quantity
Lower Bound= 0
Upper Bound= 9.5
Number of Outliers= 171
Min value= 1
Max value= 14
----------------------------------------
----------------------------------------
Column= Sales
Lower Bound= 0
Upper Bound= 498.92625
Number of Outliers= 1171
Min value= 0.444
Max value= 121504.0
----------------------------------------
----------------------------------------
Column= Discount
Lower Bound= 0
Upper Bound= 0.5
Number of Outliers= 861
Min value= 0.0
Max value= 0.8
----------------------------------------

In [165]:
#handling of the missing value

#Filling missing value of coustmer name with"unknown"
sales_clean["Customer Name"] = sales_clean["Customer Name"].fillna("Unkown")

# removing the missing rows of postal code
sales_clean =sales_clean.dropna(subset=["Postal Code"])

#fill the values of sales and profit
for col in ["Sales", "Profit"]:
    sales_clean[col] = sales_clean[col].fillna(sales_clean[col].median())

# Verify Missing values
print("Missing value after treatement=")
print(sales_clean.isnull().sum())

Missing value after treatement=
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [168]:
# Removing the duplicated rows
sales_clean = sales_clean.drop_duplicates()
rows_after_duplicates = sales_clean.shape[0]

print("Duplicate rows found before cleaning:", duplicate_before)
print("Rows remaining after duplicate removal:", rows_after_duplicates)
print("Duplicate rows after cleaning:", sales_clean.duplicated().sum())
print("Duplicate Rows has been removed!")

#Check the data type
print("Data Type before Conversion")
print("="*40)
print(sales_clean[["Order Date","Ship Date"]].dtypes)

# Order Date and Ship Date after Conversion into date time format
sales_clean["Order Date"]= pd.to_datetime(sales_clean["Order Date"] , format ="mixed")
sales_clean["Ship Date"] = pd.to_datetime(sales_clean ["Ship Date"], format="mixed")
print()
print("Data Type after Conversion")
print("="*40)
print(sales_clean[["Order Date","Ship Date"]].dtypes)
print("Order Date and Ship Date has been succesfully converted into date time format")
print()

# Removing Extra Spaces
# Data Cleaning removing leading and trailing spaces and using standard captilization
text_cols = sales_clean.select_dtypes( include= ["object","string"]).columns
for col in text_cols:
  sales_clean[col] = sales_clean[col].str.strip().str.title()
print("Text Cleaning have been completed")
print(list(text_cols))
print()

# Verify the cleaned dataset
print("Cleaned Dataset Information:")
sales_clean.info()
print()

print("Missing values after cleaning:")
print(sales_clean.isnull().sum())
print()

print("Duplicate rows after cleaning:", sales_clean.duplicated().sum())

Duplicate rows found before cleaning: 48
Rows remaining after duplicate removal: 9954
Duplicate rows after cleaning: 0
Duplicate Rows has been removed!
Data Type before Conversion
========================================
Order Date    datetime64[ns]
Ship Date     datetime64[ns]
dtype: object

Data Type after Conversion
========================================
Order Date    datetime64[ns]
Ship Date     datetime64[ns]
dtype: object
Order Date and Ship Date has been succesfully converted into date time format

Text Cleaning have been completed
['Order ID', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name']

Cleaned Dataset Information:
<class 'pandas.core.frame.DataFrame'>
Index: 9954 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9954 non-null   int64
 1   Order ID       9954 non-null   object
 2   Order Date     9954 non-null   datetime64[ns]
 3   Ship Date      9954 non-null   datetime64[ns]
 4   Ship Mode      9954 non-null   object
 5   Customer ID    9954 non-null   object
 6   Customer Name  9954 non-null   object
 7   Segment        9954 non-null   object
 8   Country        9954 non-null   object
 9   City           9954 non-null   object
 10  State          9954 non-null   object
 11  Postal Code    9954 non-null   float64
 12  Region         9954 non-null   object
 13  Product ID     9954 non-null   object
 14  Category       9954 non-null   object
 15  Sub-Category   9954 non-null   object
 16  Product Name   9954 non-null   object
 17  Sales          9954 non-null   float64
 18  Quantity       9954 non-null   int64
 19  Discount       9954 non-null   float64
 20  Profit         9954 non-null   float64
dtypes: datetime64[ns](2), float64(4), int64(2), object(13)
memory usage: 1.7+ MB

Missing values after cleaning:
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

Duplicate rows after cleaning: 0

In [169]:
# Data Cleaning Report

rows_after_cleaning = sales_clean.shape[0]

print("DATA CLEANING REPORT")
print("=" * 50)

print("1. Missing Value Treatment")
print("Missing columns before cleaning:")
print(missing_before[missing_before > 0])
print("Missing values were handled using fillna() and dropna().")
print()

print("2. Duplicate Removal Summary")
print("Duplicate rows found:", duplicate_before)
print("Rows before cleaning:", rows_before)
print("Rows after cleaning:", rows_after_cleaning)
print()

print("3. Data Type Corrections")
print("Order Date and Ship Date were converted to datetime.")
print("Postal Code was converted to integer after removing missing values.")
print()

print("4. Text Cleaning Summary")
print("Extra spaces were removed from text columns using str.strip().")
print()

print("Final Conclusion")
print("="*50)
print("1. Missing values have been handled.")
print("2. Duplicate rows have been removed.")
print("3. Date columns are now in datetime format.")
print("4. Text columns are cleaned.")
print("5. The dataset is ready for feature engineering and analysis.")
print("6. The data loss cleaning.",(len(df)-len(sales_clean))/len(df)*100)

DATA CLEANING REPORT
==================================================
1. Missing Value Treatment
Missing columns before cleaning:
Customer Name    40
Postal Code      40
Sales            40
Profit           40
dtype: int64
Missing values were handled using fillna() and dropna().

2. Duplicate Removal Summary
Duplicate rows found: 48
Rows before cleaning: 10044
Rows after cleaning: 9954

3. Data Type Corrections
Order Date and Ship Date were converted to datetime.
Postal Code was converted to integer after removing missing values.

4. Text Cleaning Summary
Extra spaces were removed from text columns using str.strip().

Final Conclusion
==================================================
1. Missing values have been handled.
2. Duplicate rows have been removed.
3. Date columns are now in datetime format.
4. Text columns are cleaned.
5. The dataset is ready for feature engineering and analysis.
6. The data loss cleaning. 0.8960573476702508

# **Feature Engineering**

In [172]:
# Feature Engineering
# ==========================

# Ensure 'Order Date' and 'Ship Date' are datetime objects
sales_clean["Order Date"] = pd.to_datetime(sales_clean["Order Date"], format="mixed")
sales_clean["Ship Date"] = pd.to_datetime(sales_clean["Ship Date"], format="mixed")

# 1. Create Order Year
sales_clean["Order Year"] = sales_clean["Order Date"].dt.year


# 2. Create Order Month
sales_clean["Order Month"] = sales_clean["Order Date"].dt.month_name()
sales_clean["Order Month Number"] = sales_clean["Order Date"].dt.month

# 3. Create Delivery Days
sales_clean["Delivery Days"] = (
    sales_clean["Ship Date"] - sales_clean["Order Date"]
).dt.days

# 4. Create Profit Margin
sales_clean["Profit Margin"] = (
    sales_clean["Profit"] / sales_clean["Sales"]
) * 100

# 5. Create Profit Status
sales_clean["Profit Status"] = np.where(sales_clean["Profit"] > 0,"Profit","Loss")
#print 5 rows
sales_clean.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sales,Quantity,Discount,Profit,Order Year,Order Month,Order Month Number,Delivery Days,Profit Margin,Profit Status
0,1,Ca-2016-152156,2016-11-08,2016-11-11,Second Class,Cg-12520,Claire Gute,Consumer,United States,Henderson,...,261.9600,2,0.00,41.9136,2016,November,11,3,16.00,Profit
1,2,Ca-2016-152156,2016-11-08,2016-11-11,Second Class,Cg-12520,Claire Gute,Consumer,United States,Henderson,...,731.9400,3,0.00,219.5820,2016,November,11,3,30.00,Profit
2,3,Ca-2016-138688,2016-06-12,2016-06-16,Second Class,Dv-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,14.6200,2,0.00,6.8714,2016,June,6,4,47.00,Profit
3,4,Us-2015-108966,2015-10-11,2015-10-18,Standard Class,So-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,957.5775,5,0.45,-383.0310,2015,October,10,7,-40.00,Loss
4,5,Us-2015-108966,2015-10-11,2015-10-18,Standard Class,So-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,22.3680,2,0.20,2.5164,2015,October,10,7,11.25,Profit

In [173]:
# QUESTIONS & ANSWERS
# ==========================

most_orders_year = sales_clean["Order Year"].value_counts().idxmax()

most_orders_month = sales_clean["Order Month"].value_counts().idxmax()

avg_delivery_time = sales_clean["Delivery Days"].mean()

avg_profit_margin = sales_clean["Profit Margin"].mean()

loss_making_orders = sales_clean[
    sales_clean["Profit Status"] == "Loss"
]

print("1. Year with most orders:", most_orders_year)
print("2. Month with most orders:", most_orders_month)
print("3. Average delivery time:", round(avg_delivery_time, 2), "days")
print("4. Number of loss-making orders:", loss_making_orders.shape[0])
print("5. Average profit margin:", round(avg_profit_margin, 2), "%")

print("\nLoss-making Orders Sample:")
print(
    loss_making_orders[
        ["Order ID",
         "Category",
         "Sub-Category",
         "Sales",
         "Profit",
         "Profit Status"]
    ].head()
)

1. Year with most orders: 2017
2. Month with most orders: November
3. Average delivery time: 3.96 days
4. Number of loss-making orders: 1922
5. Average profit margin: 12.12 %

Loss-making Orders Sample:
          Order ID         Category Sub-Category      Sales     Profit  \
3   Us-2015-108966        Furniture       Tables   957.5775  -383.0310
14  Us-2015-118983  Office Supplies   Appliances    68.8100  -123.8580
15  Us-2015-118983  Office Supplies      Binders     2.5440    -3.8160
23  Us-2017-156909        Furniture       Chairs    71.3720    -1.0196
27  Us-2015-150630        Furniture    Bookcases  3083.4300 -1665.0522

   Profit Status
3           Loss
14          Loss
15          Loss
23          Loss
27          Loss

# **Group By**

In [174]:
# Group By with single Column with agg
sales_clean.groupby("Category")["Sales"].agg(["sum","mean","max","min","count"])


#Group By with Multiple Column without agg
print("           Show Sales with Region Wise")
print("="*50)
sales_by_region = sales_clean.groupby(["Region"])["Sales"].sum().sort_values(ascending=False)
print(sales_by_region)
print()


print("          Show Sales with Sement Wise")
print("="*50)
print(sales_clean.groupby(["Category","Segment"])["Sales"].sum())

# Total Porfit by Category
print("          Show profit by Category")
print("="*50)
print(sales_clean.groupby("Category")["Profit"].sum().sort_values(ascending=False))


#Group By with Multiple Column without agg
sales_clean.groupby(["Category","Region"])["Sales"].agg(["sum","mean","max","min","count"])
print()

# Monthly sales trend
print(sales_clean.groupby(["Order Year", "Order Month Number"])["Sales"].sum())

           Show Sales with Region Wise
==================================================
Region
West       752987.6825
East       666026.8740
Central    596621.1304
South      511736.0410
Name: Sales, dtype: float64

          Show Sales with Sement Wise
==================================================
Category         Segment
Furniture        Consumer       518528.5520
                 Corporate      227178.9374
                 Home Office    127177.0195
Office Supplies  Consumer       379713.1280
                 Corporate      229042.4780
                 Home Office    124214.6240
Technology       Consumer       503896.7230
                 Corporate      245831.6270
                 Home Office    171788.6390
Name: Sales, dtype: float64
          Show profit by Category
==================================================
Category
Technology         140863.6819
Office Supplies    122816.8196
Furniture           18179.4889
Name: Profit, dtype: float64

Order Year  Order Month Number
2014        1                      14236.8950
            2                       4519.8920
            3                      57198.6410
            4                      28166.5130
            5                      23648.2870
            6                      34454.9676
            7                      33798.0790
            8                      27892.1285
            9                      81414.9708
            10                    129521.8010
            11                     78576.6527
            12                     69797.4105
2015        1                      18174.0756
            2                      11308.8290
            3                      37512.7076
            4                      33869.7465
            5                      30131.6865
            6                      28533.9660
            7                      28765.3250
            8                      37321.6922
            9                      63693.0920
            10                     31048.4935
            11                     89884.6435
            12                     74894.3812
2016        1                      18477.6270
            2                      22978.8150
            3                      51676.6090
            4                      38750.0390
            5                      56810.0040
            6                      40182.9660
            7                     157734.3270
            8                      31164.4963
            9                      89508.1089
            10                     59694.4330
            11                     79403.1458
            12                     96974.3390
2017        1                      44012.4880
            2                      20216.6874
            3                      58170.8468
            4                      36303.1841
            5                      44210.7582
            6                      52854.0097
            7                      45264.4160
            8                      63120.8880
            9                      85751.0940
            10                     66579.7492
            11                    116015.7910
            12                     83152.0288
Name: Sales, dtype: float64

In [175]:
# Final data quality check
print("Final Shape Rows,Columns=", sales_clean.shape)
print()
print("Missing Values")
print(sales_clean.isnull().sum())
print()
print("Duplicate Rows=", sales_clean.duplicated().sum())

Final Shape Rows,Columns= (9954, 27)

Missing Values
Row ID                0
Order ID              0
Order Date            0
Ship Date             0
Ship Mode             0
Customer ID           0
Customer Name         0
Segment               0
Country               0
City                  0
State                 0
Postal Code           0
Region                0
Product ID            0
Category              0
Sub-Category          0
Product Name          0
Sales                 0
Quantity              0
Discount              0
Profit                0
Order Year            0
Order Month           0
Order Month Number    0
Delivery Days         0
Profit Margin         0
Profit Status         0
dtype: int64

Duplicate Rows= 0

In [178]:
# Download the clean file
sales_clean.to_excel("Ecommerce_Cleaned_Data.xlsx", index=False)

from google.colab import files

files.download("Ecommerce_Cleaned_Data.xlsx")